GET http://localhost:3001/api/wanaka/token/validate HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjbGllbnRfY3JlZGVudGlhbHMiLCJleHAiOjE3ODczMjg1MDUsInN1YiI6IjkyNTI1ODQwIn0.i5oFD4av6Me_jV8IZjDKfNOaBlxkv4nk4IhkBFTDN-A
x-client-id: client_credentials