GET http://localhost:3001/api/wanaka/token/validate HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjbGllbnRfY3JlZGVudGlhbHMiLCJleHAiOjE3NzM0MjU5NDQsInN1YiI6IjkyNTI1ODQwIn0.kVjxPDqJvy0aA1V1PA8wD0hyxy6-VYeQ5xYmRcbqknc
x-client-id: client_credentials